Feature/daniel
Black-And-White-Solutions/black-and-white-solutions.github.io pull request #4
Opened 2021-04-27 23:18 UTC by albertwilliamsxyz

2021-04-28 23:59 UTC, GGabrielDev requested changes
Primer vistazo al PR. Todavia quedan cosas por señalar.

2021-04-28 23:59 UTC, GGabrielDev commented on githooks/pre-commit
> +#!/bin/bash
Albert modifico este archivo, sugiero que se mantenga el cambio realizado por el, esta es la primera iteración de este hook.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Form.jsx
>  const Form = ({ formId }) => {
Remover la prop `formId` hasta ser requerida en el desarrollo.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Form.jsx
>    const handleSubmit = (e) => {
Remover funcion `handleSubmit` hasta ser necesaria en el desarrollo.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Form.jsx
> +            <form id={formId} onSubmit={handleSubmit} className="form">
Remover la ID `{formID}` y el atributo `onSubmit={handleSubmit}` hasta ser necesario en el desarrollo.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Form.jsx
>        <button type="submit" className="font bold submitButton">
Estilizar y ajustar este boton al sistema de grilla del Bootstrap.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Navbar.jsx
>  import './Styles/Navbar.css'
Corregir inconsistencia en la distinción en el nombre de la carpeta e ubicación de las hojas de estilos. (Este CSS esta ubicado en una nueva carpeta cuyo nombre esta en distinción Title Case, en lugar de All Lowercase, que es el estándar que estamos usando para el nombrado de las carpetas.)

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
>  import './Styles/Presentation.css'
Corregir inconsistencia en la distinción en el nombre de la carpeta e ubicación de las hojas de estilos.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
> +import  phone_showcase  from '../img/phoneShowcase.png';
Substituir distinción de letras de la variable `phone_showcase` de Snake Case a Camel Case.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
> +    const [ColorChange, setColorChange] = useState(false);
Substituir distinción de letras de la variable `ColorChange` de Title Case a Camel Case.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
> +          <div className = { ColorChange ? 'section ColorChange': 'section' }>
Substituir distinción de letras de la variable `ColorChange` de Title Case a Camel Case.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
> +                  <img src={ phone_showcase } alt=""/>
Substituir distinción de letras de la variable `phone_showcase` de Snake Case a Camel Case.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Proceso.jsx
> +import './Styles/Proceso.css'
Corregir inconsistencia en la distinción en el nombre de la carpeta e ubicación de las hojas de estilos.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Proceso.jsx
> +        <>
Esta contracción del componente Fragment es innecesaria en el caso de uso de este componente.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Services.jsx
> +        <>
Esta contracción del componente Fragment es innecesaria en el caso de uso de este componente.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Styles/Presentation.css
> +/*--------------------------------------------------------------
Eliminar comentario.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    color: rgb(0, 0, 0);
Cambiar a RGBA por consistencia.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    color:rgb(161, 161, 161);
Cambiar a RGBA por consistencia.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    color:rgb(161, 161, 161);
Cambiar a RGBA por consistencia.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    color: rgb(255, 255, 255);
Cambiar a RGBA por consistencia.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    font-family: 'Rufina', sans-serif;
Para el tema de las fuentes recomuendo crear una clase Font con las propiedades mas genericas que se compartan con todas las demas instancias y luego crear variables las cuales carguen despues de la base.
```suggestion
    .font{
        font-family: 'Rufina', sans-serif;
        text-align: center;
        font-size: 24px;
    }
```

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +    font-size:11px;
De preferencia utilizar numeros pares a la hora de dimensionar las fuentes.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/styles/Team.css
> +@import url('https://fonts.googleapis.com/css2?family=Rufina&display=swap');
En este CSS hay 5 tamaños distintos de fuente, evaluar si es realmente necesario el que haya tantas diferencias en la fuente.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Footer.jsx
> +import React from 'react';
Este componente necesita rehacerse por completo.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Presentation.jsx
> +        <>
Esta contracción del componente Fragment es innecesaria en el caso de uso de este componente.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Navbar.jsx
> +      <>
Esta contracción del componente Fragment es innecesaria en el caso de uso de este componente.

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Proceso.jsx
> +                    </div>
Potencial componente.
```suggestion
    const SuggestedComponent = ({ containerPlace, containerColor, number, iconCSS, title, content }) => {
        const invertColor;
        if (contentColor == "white"){
            invertColor = "black";
        } else {
            invertColor = "white"
        };
    
        return(
            <div className=`containerAbout containerAbout-${ containerPlace }`>
                <div className=`image box-${ containerColor }`><h1 className=`text-center pt-2 text-${ containerColor }`>{ value }</h1></div>
                <div className=`content { invertColor }-box`>
                    <h3 className="aboutTitle text-center"><i className=`${ iconCSS } me-3`></i>{ title }</h3>
                    <p  className="text-center">{ content }</p>
                </div>
            </div>
        );
    };
    
    SuggestedComponent.propTypes = {
        containerPlace: PropTypes.oneOf(['left', 'right']),
        containerColor: PropTypes.oneOf(['white', 'black']),
        number: PropTypes.number,
        iconCSS: PropTypes.string,
        title: PropTypes.string,
        content: PropTypes.string
    };
```

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Services.jsx
> +                        </div>
Posible componente.
```suggestion
    const SuggestedComponent = ({ containerDelay, containerColor, iconCSS, title, content }) => {
    
        const invertColor;
        if (contentColor == "white"){
            invertColor = "black";
        } else {
            invertColor = "white"
        };
    
        return(
            <div className="col-sm-7 col-md-6" data-aos="fade-up" data-aos-delay={ containerDelay }>
                <div className=`service-box box-${containerColor}`>
                    <h3 className=`serviceCardTitle title-${invertColor}`><i className=`${ iconCSS } me-3`></i>{ title }</h3>
                    <p>{ content }</p>
                </div>
            </div>
        );
    };
    
    SuggestedComponent.propTypes = {
        containerDelay: PropTypes.number,
        containerColor: PropTypes.oneOf(['white', 'black']),
        iconCSS: PropTypes.string,
        title: PropTypes.string,
        content: PropTypes.string
    };
```

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Team.jsx
> +                        </div>
Posible componente.
```suggestion
    const SuggestedComponent = ({ cardName, cardTitle, cardPhoto, cardContent }) => {
        return (
            <div className="col-md-3 col-lg-3 item">
                <div className="box">
                    <h3 className="name">{ cardName }</h3>
                    <p className="title">{ cardTitle }</p>
                    <img src={ cardPhoto } alt=""/>
                    <p className="description">{ cardContent }</p>
                    <div className="social"><a href="/#"><i className="fab fa-linkedin"></i></a><a href="/#"><i className="fab fa-twitter-square"></i></a><a href="/#"><i className="fab fa-github"></i></a></div>
                </div>
            </div>
        );
    };
    
    SuggestedComponent.propTypes = {
        cardName: PropTypes.string,
        cardTitle: PropTypes.string,
        cardPhoto: PropTypes.string,
        cardContent: PropTypes.string
    };
```

2021-04-28 23:59 UTC, GGabrielDev commented on src/components/Team.jsx
> +                                <div className="social"><a href="/#"><i className="fab fa-linkedin"></i></a><a href="/#"><i className="fab fa-twitter-square"></i></a><a href="/#"><i className="fab fa
Posible componente.
```suggestion
    const SuggestedComponent = ({ urlLinkedIn, urlTwitter, urlGithub }) => {
        return(
            <div className="social">
                <a href={ urlLinkedIn }><i className="fab fa-linkedin"></i>
                <a href={ urlTwitter }><i className="fab fa-twitter-square"></i></a>
                <a href={ urlGithub }><i className="fab fa-github"></i></a>
            </div>
        );
    };
    
    SuggestedComponent.propTypes = {
        urlLinkedIn: PropType.string,
        urlTwitter: PropType.string,
        urlGithub; PropType.string
    };
```

2021-04-29 14:15 UTC, albertwilliamsxyz commented on githooks/pre-commit
> +# Re-add files since they may have been fixed
Usa comentarios a lo largo de todo el script o no los uses en ningun lado, mantener consistencia @GGabrielDev

2021-04-29 14:15 UTC, albertwilliamsxyz commented on public/index.html
> +
Remover espacio en blanco

2021-04-29 14:15 UTC, albertwilliamsxyz commented on public/index.html
> +		<script src="https://kit.fontawesome.com/b6b1420091.js" crossorigin="anonymous"></script>
Fixear identacion

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/components/Presentation.jsx
> +import  phone_showcase  from '../img/phoneShowcase.png';
Deberia haber un espacio entre cada token

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/components/Proceso.jsx
> +const Proceso = () => {
El nombre del componente debe ser reemplazado, todos los nombres deberian estar en ingles

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/App.js
> +      <Proceso />
El nombre del componente debe ser reemplazado, todos los nombres deberian estar en ingles

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/components/Proceso.jsx
> +                    </div>
```suggestion
const white = "white";
const black = "black";

const TimelineItem = ({ containerPlace, containerColor, number, iconCSS, title, content }) => {
	const invertColor = contentColor == white ? white: black;

	return(
		<div className=`containerAbout containerAbout-${ containerPlace }`>
			<div className=`image box-${ containerColor }`>
				<h1 className=`text-center pt-2 text-${ containerColor }`>{ value }</h1>
			</div>
			<div className=`content ${ invertColor }-box`>
				<h3 className="aboutTitle text-center"><i className=`${ iconCSS } me-3`></i>{ title }</h3>
				<p  className="text-center">{ content }</p>
			</div>
		</div>
	);
};

TimelineItem.propTypes = {
	containerPlace: PropTypes.oneOf(['left', 'right']),
	containerColor: PropTypes.oneOf(['white', 'black']),
	number: PropTypes.number,
	iconCSS: PropTypes.string,
	title: PropTypes.string,
	content: PropTypes.string
};
```

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/components/Proceso.jsx
> +                    </div>
```suggestion
const Timeline = ({ listOfItems }) => {
	const timelineItems = [];
	listOfItems.forEach((item, index) => {
		const index_is_even = index % 2 === 0;
		timelineItems.push({
			containerPlace: index_is_even ? 'left': 'right',
			containerColor: index_is_even ? 'white': 'black',
			number: index + 1,
			iconCSS: item.iconCSS,
			title: item.title,
			content: item.content
		});
	});
	return (
		<div className="container timeline mb-5">
			listOfItems.map(TimelineItem);
		</div>
	);
}
```

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/components/Services.jsx
> +                        </div>
```suggestion
const CardContent = ({ iconCSS, title, content }) => {
	return (
		<h3 className="aboutTitle text-center"><i className=`${ iconCSS } me-3`></i>{ title }</h3>
		<p className="text-center">{content}</p>
	);
}
```

2021-04-29 14:15 UTC, albertwilliamsxyz commented on src/App.js
> +      <Team />
Crear componente Layout, conteniendo las secciones (Presentation, Services, Form, Process)

2021-05-03 14:46 UTC, GGabrielDev commented on src/components/Navbar.jsx
>                  <ul className="navbar-nav my-auto mb-2 mb-lg-0">
Hacer que la Barra de direcciones genere las entradas a demanda en lugar de hard-coded.

2021-05-03 14:46 UTC, GGabrielDev commented on src/components/Navbar.jsx
>                <div className="collapse navbar-collapse" id="navbarText">
Hacer que la barra de direcciones genere las direcciones a demanda en lugar de hard-coded.

2021-05-04 00:46 UTC, merged